iter13
GaryShem/ya-metrics pull request #13
Opened 2024-05-12 02:08 UTC by GaryShem

2024-05-12 11:20 UTC, gonozov0 requested changes
Отличная работа 👍
Оставил пару комментариев по улучшению кода

2024-05-12 11:20 UTC, gonozov0 commented on internal/server/handlers/update.go
> +	case string(models.TypeCounter):
Сделай лучше так, чтобы metricType была того же типа и не нужно было к строке приводить везде

2024-05-12 11:20 UTC, gonozov0 commented on internal/server/handlers/update.go
> +		logging.Log.Debug("error decoding request json", zap.Error(err))
Не совсем понимаю, почему это уровень DEBUG
Ты отдаешь 500, поэтому это должно логироваться как критическая ошибка в твоей системе

2024-05-12 11:20 UTC, gonozov0 commented on internal/server/handlers/update.go
> +		logging.Log.Debug("error decoding request json", zap.Error(err))
И везде ниже также

2024-05-12 11:20 UTC, gonozov0 commented on internal/server/run.go
> +	DBString        *string
Не понимаю, почему решил сделать все типы ссылочными
у тебя везде в логике все равно происходит их приведение к значению, сделай по значению

2024-05-12 11:20 UTC, gonozov0 commented on internal/server/run.go
> +	DBString        *string
Ты таким образом лишь увеличиваешь риск возможных паник в рантайме

2024-05-12 11:20 UTC, gonozov0 commented on internal/server/storage/memorystorage/metric.go
> +func (ms *MemStorage) UpdateMetricBatch(metrics []*models.Metrics) ([]*models.Metrics, error) {
у тебя слайс уже ссылочный тип, нету смысла писать []*models.Metrics, я не вижу валидного кейса, когда ты бы ожидал nil значение внутри слайса
Для улучшения производительности и уменьшения неожиданных паник замени везде на []models.Metrics

2024-05-12 11:20 UTC, gonozov0 commented on internal/server/storage/postgres/counter.go
> +	result := make(map[string]*models.Counter)
map[string]models.Counter

2024-05-12 11:20 UTC, gonozov0 commented on internal/server/storage/postgres/metric.go
> +func (s *SQLStorage) UpdateMetric(m *models.Metrics) error {
здесь тоже не совсем понимаю почему ссылку передаешь, ты не ожидаешь нигде nil, передавай по значению

2024-05-12 11:20 UTC, gonozov0 commented on internal/server/storage/postgres/metric.go
> +func (s *SQLStorage) UpdateMetric(m *models.Metrics) error {
В других местах также везде поправь

2024-05-12 11:20 UTC, gonozov0 commented on internal/server/storage/postgres/metric.go
> +		row := models.NewGauge("", 0)
вызов конструктора тут явно не нужен, просто models.Gauge{}

2024-05-12 11:20 UTC, gonozov0 commented on internal/server/storage/postgres/metric.go
> +		row := models.NewGauge("", 0)
в других местах аналогично

2024-05-13 02:50 UTC, GaryShem commented on internal/server/storage/memorystorage/metric.go
> +func (ms *MemStorage) UpdateMetricBatch(metrics []*models.Metrics) ([]*models.Metrics, error) {
nil внутри слайса не нужен, это скорее для избежания лишних копирований при манипуляциях со слайсами, т.к. их довольно много

2024-05-13 02:52 UTC, GaryShem commented on internal/server/storage/postgres/metric.go
> +		row := models.NewGauge("", 0)
Это в основном для заполнения поля field: "gauge" меньшим количеством кода, плюс избежание ошибок (опечатки в инициализации уже случались).

2024-05-19 16:05 UTC, GaryShem commented on internal/server/storage/postgres/metric.go
> +func (s *SQLStorage) UpdateMetric(m *models.Metrics) error {
> здесь тоже не совсем понимаю почему ссылку передаешь, ты не ожидаешь нигде nil, передавай по значению

Мы же должны вернуть изменённое значение метрики. Копирование сделает копию, для которой потом не поменять оригинал, разве нет?

2024-05-19 16:21 UTC, GaryShem commented on internal/server/storage/postgres/metric.go
> +func (s *SQLStorage) UpdateMetric(m *models.Metrics) error {
К тому же, UpdateMetric всё-таки может отдать null, если провалится валидация входящей метрики (тип, имя)

2024-05-19 17:22 UTC, GaryShem commented on internal/server/run.go
> +	DBString        *string
> Не понимаю, почему решил сделать все типы ссылочными у тебя везде в логике все равно происходит их приведение к значению, сделай по значению

Потому что библиотека flag требует ссылочных типов для полей. Для введения значений придётся сделать отдельный тип

2024-05-21 08:02 UTC, gonozov0 commented on internal/server/storage/postgres/metric.go
> +func (s *SQLStorage) UpdateMetric(m *models.Metrics) error {
Если что-то хочешь вернуть после UpdateMetric, то тогда правильнее это будет явно и возвращать
Как-то модифицировать входные структуры - это антипаттерн, которого нужно стараться всегда избегать

2024-05-21 08:03 UTC, gonozov0 commented on internal/server/storage/memorystorage/metric.go
> +func (ms *MemStorage) UpdateMetricBatch(metrics []*models.Metrics) ([]*models.Metrics, error) {
слайс - это всегда уже ссылочный тип, у тебя не будет происходить никакого копирования под капотом

2024-05-21 08:04 UTC, gonozov0 commented on internal/server/storage/memorystorage/metric.go
> +func (ms *MemStorage) UpdateMetricBatch(metrics []*models.Metrics) ([]*models.Metrics, error) {
тем более ты сделал ссылку не на слайс, а на слайс со ссылками на каждый его элемент, при любом обращении к элементу это будет поход в кучу, и эта операция довольно долгая

2024-05-21 08:06 UTC, gonozov0 commented on internal/server/run.go
> +	DBString        *string
когда ты передаешь значения в flag, просто передавай по ссылке через "&", не стоит из-за этого все типы делать ссылочными

2024-05-21 08:07 UTC, gonozov0 approved these changes
Основные моменты поправлены 👍

2024-05-27 19:54 UTC, merged