Iter5
GaryShem/ya-metrics pull request #5
Opened 2024-04-06 22:54 UTC by GaryShem

2024-04-07 11:12 UTC, gonozov0 requested changes
Отличная работа 👍
Оставил пару комментариев по улучшению кода

Если есть желание, рекомендую сразу подключить к проекту [golangci-lint](https://golangci-lint.run/) и [golden config](https://gist.github.com/maratori/47a4d00457a92aa426dbd48a18776322) для него. Это позволит тебе сразу писать код native go стиле и привыкать к этому.
Для удобства лучше также [установить](https://github.com/gonozov0/go-echo-ddd-template/tree/main?tab=readme-ov-file#pre-commit-hooks) и [настроить](https://github.com/gonozov0/go-echo-ddd-template/blob/main/.pre-commit-config.yaml#L22) precommit хуки, чтобы линтер отрабатывал перед каждым коммитом
Дополнительно можно и в [ci добавить](https://github.com/gonozov0/go-echo-ddd-template/blob/main/.github/workflows/lint%26test.yml#L51)

2024-04-07 11:12 UTC, gonozov0 commented on cmd/agent/flags.go
> +//}
видимо забыл удалить

2024-04-07 11:12 UTC, gonozov0 commented on cmd/agent/flags.go
> +	//}
Аналогично, по своему опыту лучше отучать себя комментить ненужный код, и сразу его удалять.
Переживать, что не сможешь вернуть не стоит, всегда есть история git и cmd + Z

2024-04-07 11:12 UTC, gonozov0 commented on cmd/agent/main.go
> +}
Это бизнес логика и ее стоит положить в internal/agent/

2024-04-07 11:12 UTC, gonozov0 commented on cmd/agent/main.go
> +	}
Все, кроме parseFlags стоит положить в internal/agent/run.go в функцию Run, т.к. это бизнес логика, которую важно тестировать.
А тесты не должны импортировать ничего из main

2024-04-07 11:12 UTC, gonozov0 commented on cmd/agent/main.go
> +		collectionDelay -= sleepTime
отлично придумал

2024-04-07 11:12 UTC, gonozov0 commented on cmd/agent/main.go
Как я вижу, сейчас нету тестов на логику агента, хорошо бы написать, можно даже без моков, чтобы тесты требовали запущенный сервер

2024-04-07 11:12 UTC, gonozov0 commented on cmd/server/flags.go
> +//}
аналогично

2024-04-07 11:12 UTC, gonozov0 commented on cmd/server/flags.go
> +	//}
аналогично

2024-04-07 11:12 UTC, gonozov0 commented on cmd/server/main_test.go
> +}
Довольно сложно воспринимать 4 теста в одном, разбей хотя бы тесты на GET и POST на разные. Высший пилотаж - это использовать Suite ([как пример](https://github.com/gonozov0/go-echo-ddd-template/blob/main/internal/application/users/handlers/handlers_test/suite_test.go#L14)) (пример [get](https://github.com/gonozov0/go-echo-ddd-template/blob/main/internal/application/users/handlers/handlers_test/get_test.go) и [post](https://github.com/gonozov0/go-echo-ddd-template/blob/main/internal/application/users/handlers/handlers_test/create_test.go))

2024-04-07 11:12 UTC, gonozov0 commented on cmd/server/main_test.go
Тестов в cmd быть не должно, т.к. в будущем у тебя появится новая логика и тогда этот файл разрастется на тысячу строк и совсем не будет отображать содержимое тестов

Т.к. тут ты тестируешь хендлеры, то эти тесты стоит перенести в internal/server/handlers/handlers_test/

2024-04-07 11:12 UTC, gonozov0 commented on cmd/server/main.go
> +}
Аналогично, в main только парсинг флагов + server.Run с обработкой ошибки и паникой в ее случае, остальное в internal/server

2024-04-07 11:12 UTC, gonozov0 commented on internal/storage/memStorage.go
Отлично выделил collector и storage, но не стоит их помещать в одно место, т.к. collector относится к агенту, а storage к серверу, то стоит поместить в internal/agent/collector и internal/server/storage соответственно

Если при этом используется что-то общее между частями сервера и агента, то это можно положить в internal/shared/ и переиспользовать в обоих частях проекта

2024-04-07 11:12 UTC, gonozov0 commented on internal/storage/memStorage.go
> +}
Лучше объяви этот интерфейс и хендлерах и сделай так, чтобы хенедлеры принимали его, так получится более абстрактная реализация с возможностью более легкого внедрения DBStorage в дальнейших спринтах

2024-04-07 11:12 UTC, gonozov0 commented on internal/handlers/metrics.go
> +	return func(w http.ResponseWriter, r *http.Request) {
Вместо возврата функции во всех хендлерах лучше объявить [структуру хендлер, принимающий MemStorage (а еще лучше интерфейс)](https://github.com/gonozov0/go-echo-ddd-template/blob/main/internal/application/users/handlers/handler.go#L14) и тогда можно сразу описывать [реальные хендлеры](https://github.com/gonozov0/go-echo-ddd-template/blob/main/internal/application/users/handlers/get.go#L19)

2024-04-07 11:12 UTC, gonozov0 commented on internal/handlers/metrics.go
> +			panic(err)
нигде, кроме main не стоит паниковать, здесь лучше често вернуть 500 и перед этим залогировать саму ошибку

2024-04-07 11:12 UTC, gonozov0 commented on internal/storage/metricCollector.go
> +			panic(err)
Нигде кроме main нельзя паниковать, здесь необходимо возвращать ошибку

2024-04-07 11:12 UTC, gonozov0 commented on cmd/agent/main.go
> +			panic(err)
аналогично

2024-04-07 11:12 UTC, gonozov0 commented on cmd/agent/main.go
> +			panic(res.StatusCode)
аналогично, + ты, отдав тут только статус код, потом вообще не поймешь, что эта за ошибка и почему она возникла, лучше вернуть ошибку с нормальным описанием проблемы

2024-04-07 11:12 UTC, gonozov0 commented on internal/handlers/metrics.go
> +			panic(err)
аналогично

2024-04-07 11:12 UTC, gonozov0 commented on cmd/agent/main.go
> +			panic(err)
аналогично

2024-04-07 11:12 UTC, gonozov0 commented on cmd/agent/main.go
> +			panic(res.StatusCode)
аналогично

2024-04-07 11:12 UTC, gonozov0 commented on internal/handlers/metrics.go
> +			panic(err)
аналогично

2024-04-07 12:05 UTC, GaryShem commented on cmd/agent/flags.go
> +	//}
Я не мог понять, почему этот фрагмент не работал, поэтому специально выложил его как часть ревью, чтобы спросить, в чём может быть проблема. 

Случайно обнаружил, что поля не парсились из-за того, что они начинались с маленькой буквы, поэтому теперь возвращаю эту версию кода

2024-04-09 07:35 UTC, gonozov0 commented on cmd/agent/flags.go
> +	//}
Если в будущем хочешь спросить что-то асинхронно при ревью, то пиши плиз перед этим коммент вида
// Вопрос ментору:

2024-04-09 07:40 UTC, gonozov0 approved these changes
Все моменты поправлены 👍

2024-04-09 17:31 UTC, merged