Iter9
GaryShem/ya-metrics pull request #9
Opened 2024-04-28 21:03 UTC by GaryShem

2024-04-28 21:25 UTC, GaryShem commented on internal/server/longterm/file.go
> +		interval = time.Millisecond * 100
Как правильно обработать ситуацию с реалтаймом? Можно врезаться в сам сторадж, но это выглядит не очень хорошо

2024-04-29 16:58 UTC, gonozov0 requested changes
Отличная работа 👍

2024-04-29 16:58 UTC, gonozov0 commented on internal/agent/run.go
> +	return <-c
похвально, что уже разобрался с каналами и горутинами, есть еще много конечно нюансов по их graceful запуску и обработке, но это будет в go advance
Из текущих моментов я бы убрал "trigger" из названия всех функций, когда видишь запуск в горутине и так понятно, что это будет работать в фоне

2024-04-29 16:58 UTC, gonozov0 commented on internal/agent/run_test.go
> +	//serverIP := serverURLSlice[len(serverURLSlice)-2]
если тебе не нужен serverIP, то лучше сразу удали код, а не комментируй)

2024-04-29 16:58 UTC, gonozov0 commented on internal/server/handlers/get.go
> +	}
Не вижу особого смысла, ты в при инициализации роутера управляешь тем, на какой урл и метод хендлер назначать, не стоит сюда эту логику переносить

2024-04-29 16:58 UTC, gonozov0 commented on internal/server/handlers/update.go
> +	}
аналогично тут и в других местах в этом файле

2024-04-29 16:58 UTC, gonozov0 commented on internal/server/longterm/file.go
> +	}
Эта логика должна быть в NewFileSaver, причем если передали невалидный filename, нужно отдавать ошибку
И проверять валидность лучше не длиной имени, а попыткой открытия этого файла

2024-04-29 16:58 UTC, gonozov0 commented on internal/server/longterm/file.go
> +		interval = time.Millisecond * 100
не понял, какую ситуацию с реалтаймом ты имеешь ввиду, и особенно фразу "врезаться в сторадж"

2024-04-29 16:58 UTC, gonozov0 commented on internal/server/middleware/gzip.go
> +//}
удаляй сразу ненужный код

2024-04-29 16:58 UTC, gonozov0 commented on internal/shared/storage/memorystorage/counter.go
> +func (ms *MemStorage) ResetCounter(metricName string) error {
Я не совсем понимаю, почему у тебя MemStorage является shared между агентом и серверов, отсюда я так понимаю и вытекают такие интересные методы.

Storage должен быть только для сервера, для агента тебе достаточно просто каждый раз при сборке метрик передавать новый массив стуктур с метриками

2024-04-29 19:48 UTC, GaryShem commented on internal/server/longterm/file.go
> +		interval = time.Millisecond * 100
В задании сказано, что если в качестве интервала выставлен 0, то содержимое стораджа должно сохраняться синхронно - если я правильно понимаю, имеется в виду сохранение в момент записи. Тогда не совсем понятно, как лучше организовать сохранение - ведь подход просто с таймером, строго говоря, не является верным для этой ситуации. 100мс вместо 0 - это просто костыль, который сохраняет "достаточно часто". 

"Врезаться в сторадж" - имеется в виду добавлять логику сохранения в методы самого стораджа вместо отдельной сущности, например, чтобы при каждой записи явно вызывать сохранение на диск. Однако, MemStorage очень не хочется дополнять ещё и сохранением в файл, поэтому хочется этого избежать.

Альтернативным методом могло бы стать использование объекта, аналогичного ивентам из других языков программирования типа C#, но в Go широко используются каналы, которые, кажется, всегда являются блокирующими. Тогда для каналов можно, например, создать сущность, которая будет постоянно читать канал и просто ничего не делать по получении данных из него, просто чтобы разблокировать сторадж, а в случае необходимости записи в файл передавать настоящий Writer для файла.

Но тесты проходятся и так, поэтому я не знаю, достаточно ли текущего варианта, или надо доработать, чтобы было строго по задаче. И, если надо доработать, то каким образом?

2024-05-01 08:17 UTC, GaryShem commented on internal/server/longterm/file.go
> +	}
Так это не проверка валидности: в задаче указано, что если в filename передаётся пустая строка, то запись на диск не нужна.

2024-05-03 12:39 UTC, gonozov0 requested changes
Ответил на вопросы, осталось еще пару issues

2024-05-03 12:39 UTC, gonozov0 commented on internal/server/longterm/file.go
> +		interval = time.Millisecond * 100
Да, в полне, тут на самом деле создатели контента курса перемудрили для трека с метриками, вы еще по факту горутины и каналы не проходили, чтобы такое давать, достоточно было бы просто делать сохранение в файл при каждом сохранении метрики

2024-05-03 12:39 UTC, gonozov0 commented on internal/server/longterm/file.go
> +	}
Дк а зачем тебе тогда в принципе использовать FileSaver?
Если передана пустая строка, то используй просто MemStorage, а в FileSaver логично должна быть валидация, что файл существует

2024-05-08 09:06 UTC, gonozov0 approved these changes
Отличная работа 💪
Все моменты поправлены

2024-05-08 09:39 UTC, merged